export const CATEGORY_TABLE = 'store_categories'
export const ENQUIRY_TABLE = 'store_enquiries'
export const PRODUCT_TABLE = 'store_products'
export const PRODUCT_SPECIFICATION_TABLE = 'store_product_specs'
export const SHOP_TABLE = 'store_shops'
export const SPECIFICATION_SECTION_TABLE = 'store_spec_sections'
export const SPECIFICATION_KEY_TABLE = 'store_spec_keys'
